subtoole/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using subtoole.Models;

namespace subtoole.Models
{
    partial class Person
    {
        public string FullName => $"{FirstName} {LastName}";
    }
}

namespace subtoole.Controllers
{
    public class PeopleController : Controller
    {
        private Entities db = new Entities();

        // GET: People
        public ActionResult Index()
        {
            if (User.IsInRole("Administraator"))
                return View(db.People.ToList());
            else return RedirectToAction("Index", "Home");
        }

        // GET: People/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }



            return View(person);
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult AddPartner(string id, string partner)
        {
            Company c = db.Companies.Find(id);
            Person p = db.People.Find(partner);
            if (c != null && p != null)
            {
                try
                {
                    c.People.Add(p);
                    db.SaveChanges();
                }
                catch { }
            }
            return RedirectToAction("Details", new { id });
        }

        public ActionResult RemovePartner(string id, string partner)
        {
            Company c = db.Companies.Find(id);
            Person p = db.People.Find(partner);
            if (c != null && p != null)
            {
                try
                {
                    c.People.Remove(p);
                    db.SaveChanges();
                }
                catch { }
            }
            return RedirectToAction("Details", new { id });
        }

        // GET: People/Create
        public ActionResult Create()
        {
            ViewBag.PictureId = new SelectList(db.Files, "Id", "Filename");

            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Email,BirtDate,Gender,IK,Address,Phone,Education,Profession,Languages,CV,PictureId")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.People.Add(person);
                db.SaveChanges();
                return RedirectToAction("Create", "Applications", new { id = person.Id});
                
            }

            ViewBag.PictureId = new SelectList(db.Files, "Id", "Filename", person.PictureId);
            return View(person);
        }

        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            ViewBag.PictureId = new SelectList(db.Files, "Id", "Filename", person.PictureId);
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email,BirtDate,Gender,IK,Address,Phone,Education,Profession,Languages,CV,PictureId")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PictureId = new SelectList(db.Files, "Id", "Filename", person.PictureId);
            return View(person);
        }

        // GET: People/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.People.Find(id);
            db.People.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

subtoole/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using subtoole.Models;

namespace subtoole.Controllers
{
    public class RolesController : Controller
    {
        private Entities db = new Entities();

        // GET: Roles
        public ActionResult Index()
        {
            return View(db.AspNetRoles.ToList());
        }


        // GET: Roles/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] AspNetRole aspNetRole)
        {
            if (ModelState.IsValid)
            {
                db.AspNetRoles.Add(aspNetRole);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetRole);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] AspNetRole aspNetRole)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetRole).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetRole);
        }

        // GET: Roles/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            if (aspNetRole == null)
            {
                return HttpNotFound();
            }
            return View(aspNetRole);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetRole aspNetRole = db.AspNetRoles.Find(id);
            db.AspNetRoles.Remove(aspNetRole);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

subtoole/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using subtoole.Models;

namespace subtoole.Controllers
{
    public class UsersController : Controller
    {
        private Entities db = new Entities();

        
        // GET: Users
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
                return View(db.AspNetUsers.ToList());
            else
                return RedirectToAction("Index", "Home");
        }

        // GET: Users/Details/5
        
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }

            ViewBag.Roles = db.AspNetRoles
                .Where(r => !r.AspNetUsers.Select(x => x.Email).Contains(aspNetUser.Email))
                .ToList();
                
            return View(aspNetUser);
        }

        public ActionResult AddRole(string id, string role)
        {
            AspNetUser u = db.AspNetUsers.Find(id);
            AspNetRole r = db.AspNetRoles.Find(role);
            if(u != null && r != null)
            {
                try
                {
                    u.AspNetRoles.Add(r);
                    db.SaveChanges();
                }
                catch { }
            }

            return RedirectToAction("Details", new { id });
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult RemoveRole(string id, string role)
        {
            AspNetUser u = db.AspNetUsers.Find(id);
            AspNetRole r = db.AspNetRoles.Find(role);
            if (u != null && r != null)
            {
                try
                {
                    u.AspNetRoles.Remove(r);
                    db.SaveChanges();
                }
                catch { }
            }

            return RedirectToAction("Details", new { id });
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DisplayName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(aspNetUser);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DisplayName,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] AspNetUser aspNetUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(aspNetUser);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

subtoole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico' />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="font-family:'Subway-Footlong'">
@if  (Request.IsAuthenticated)
{ 
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href='@Url.Action("Index", "Home")'><img width="60" src='@Url.Content("~/Content/Images/logo.png")' /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">

                @if (User.IsInRole("Administraator"))
                {
                    <li>@Html.ActionLink("Kandidaadid", "Index", "Applications", null, new { @class = "btn btn-primary"})</li>
                    <li>@Html.ActionLink("Maasikad", "Index", "People", null, new { @class = "btn btn-primary"})</li>
                    <li>@Html.ActionLink("Restod", "Index", "Companies", null, new { @class = "btn btn-primary"})</li>
                    <li>@Html.ActionLink("Kasutajad", "Index", "Users", null, new { @class = "btn btn-primary"})</li>
                    <li>@Html.ActionLink("Rollid", "Index", "Roles", null, new { @class = "btn btn-primary"})</li>
                }
                else if (User.IsInRole("Frantsiis"))
                {
                    <li>@Html.ActionLink("Kandidaadid", "Index", "Applications", null, new { @class = "btn btn-primary" })</li>
                }
                else
                {
                    <li>@Html.ActionLink("Sinu kandideerimised", "Index", "Applications", null, new { @class = "btn btn-primary" })</li>
                    @*<li>@Html.ActionLink("Kustuta kasutajakonto", "Delete", "Users", null, new { id = User, @class = "btn btn-danger" })</li>*@
                }

                @*@if (Request.IsAuthenticated)
                {
                    if (User.IsInRole("Frantsiis"))
                    {
                        <li>@Html.ActionLink("Kandidaadid", "Index", "Applications", null, new { @class = "btn btn-primary" })</li>

                        if (User.IsInRole("Administraator"))
                        {
                            <li>@Html.ActionLink("Maasikad", "Index", "People", null, new { @class = "btn btn-primary focus" })</li>
                            <li>@Html.ActionLink("Restod", "Index", "Companies", null, new { @class = "btn btn-primary" })</li>
                            <li>@Html.ActionLink("Kasutajad", "Index", "Users", null, new { @class = "btn btn-primary" })</li>
                            <li>@Html.ActionLink("Rollid", "Index", "Roles", null, new { @class = "btn btn-primary" })</li>
                        }


                    }
                    <li>@Html.ActionLink("Sinu kandideerimised", "Index", "Applications", null, new { @class = "btn btn-primary" })</li>
                    <li>@Html.ActionLink("Kustuta kasutajakonto", "Delete", "Users", null, new { id = User, @class = "btn btn-danger" })</li>
                }*@
            </ul>
                @Html.Partial("_LoginPartial")
        </div>
    </nav>
    }
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <center><p>&copy; @DateTime.Now.Year @Html.ActionLink("Subtööle", "Register", "Account")</p></center>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @*<link rel="stylesheet" href="/resources/demos/style.css">*@
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
        $(document).ready(function () {
            $('.datepicker').datepicker({
                dateFormat: 'dd.mm.yy'
            });
        });
    </script>

    <script>
        /* Estonian initialisation for the jQuery UI date picker plugin. */
        /* Written by Mart Sõmermaa (mrts.pydev at gmail com). */
        (function (factory) {
            if (typeof define === "function" && define.amd) {
                // AMD. Register as an anonymous module.
                define(["../widgets/datepicker"], factory);
            } else {
                // Browser globals
                factory(jQuery.datepicker);
            }
        }(function (datepicker) {
            datepicker.regional.et = {
                closeText: "Sulge",
                prevText: "Eelnev",
                nextText: "Järgnev",
                currentText: "Täna",
                monthNames: ["Jaanuar", "Veebruar", "Märts", "Aprill", "Mai", "Juuni",
                    "Juuli", "August", "September", "Oktoober", "November", "Detsember"],
                monthNamesShort: ["Jaan", "Veebr", "Märts", "Apr", "Mai", "Juuni",
                    "Juuli", "Aug", "Sept", "Okt", "Nov", "Dets"],
                dayNames: [
                    "Pühapäev",
                    "Esmaspäev",
                    "Teisipäev",
                    "Kolmapäev",
                    "Neljapäev",
                    "Reede",
                    "Laupäev"
                ],
                dayNamesShort: ["Pühap", "Esmasp", "Teisip", "Kolmap", "Neljap", "Reede", "Laup"],
                dayNamesMin: ["P", "E", "T", "K", "N", "R", "L"],
                weekHeader: "näd",
                dateFormat: "dd.mm.yy",
                firstDay: 1,
                isRTL: false,
                showMonthAfterYear: false,
                yearSuffix: ""
            };
            datepicker.setDefaults(datepicker.regional.et);
            return datepicker.regional.et;
        }));
    </script>
</body>
</html>